const productsSeed= [

    {
        company:"Nintendo",
        console: "Nintendo Entertainment System" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://i.ebayimg.com/images/g/tDEAAOSwSHlgODUg/s-l500.jpg",
        inCart: false,
        price: "15.00",
    },
    {
        company:"Nintendo",
        console: "Nintendo Entertainment System" ,
        product: "Display Cable",
        inStock: true,
        quantity: 12,
        img: "https://m.media-amazon.com/images/I/61bFO8I2YNL._AC_SX679_.jpg",
        inCart: false,
        price: "10.00",
    },
    {
        company:"Nintendo",
        console: "Nintendo Entertainment System" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 12,
        img: "https://m.media-amazon.com/images/I/61eOdCUqiVL._SX522_.jpg",
        inCart: false,
        price: "13.00",
    },
    {
        company:"Sega",
        console: "Master System" ,
        product: "Power Supply",
        inStock: true,
        quantity: 10,
        img: "https://m.media-amazon.com/images/I/612bupLnJhL._AC_SX679_.jpg",
        inCart: false,
        price: "20.00",
    },
    {
        company:"Sega",
        console: "Master System" ,
        product: "Display Cable",
        inStock: true,
        quantity: 20,
        img: "https://gametrog.com/wp-content/uploads/2018/08/sega-master-system-av-rca-gametrog.jpg",
        inCart: false,
        price: "12.99",
    },
    {
        company:"Sega",
        console: "Master System" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 70,
        img: "https://m.media-amazon.com/images/I/61eOdCUqiVL._SX522_.jpg",
        inCart: false,
        price: "15.00",
    },
    {
        company:"Atari",
        console: "Jaguar" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/41r0tHLlSaL._AC_UY436_FMwebp_QL65_.jpg",
        inCart: false,
        price: "14.99",
    },
    {
        company:"Atari",
        console: "Jaguar" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://gametrog.com/wp-content/uploads/2018/08/sega-master-system-av-rca-gametrog.jpg",
        inCart: false,
        price: "11.99",
    },
    {
        company:"Atari",
        console: "Jaguar" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/41r0tHLlSaL._AC_UY436_FMwebp_QL65_.jpg",
        inCart: false,
        price: "30.00",
    },
    {
        company:"Nintendo",
        console: "Super NES" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61KkXelaEZL._AC_UY436_QL65_.jpg",
        inCart: false,
        price: "16.99",
    },
    {
        company:"Nintendo",
        console: "Super NES" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61bFO8I2YNL._AC_SX679_.jpg",
        inCart: false,
        price: "18.00",
    },
    {
        company:"Nintendo",
        console: "Super NES" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61eOdCUqiVL._SX522_.jpg",
        inCart: false,
        price: "15.99",
    },
    {
        company:"Sega",
        console: "Sega CD" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/713AKrwf0OL._AC_SX679_.jpg",
        inCart: false,
        price: "16.99",
    },
    {
        company:"Sega",
        console: "Sega CD" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://gametrog.com/wp-content/uploads/2018/08/sega-master-system-av-rca-gametrog.jpg",
        inCart: false,
        price: "30.00",
    },
    {
        company:"Sega",
        console: "Sega CD" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://images.squarespace-cdn.com/content/v1/5a5a8c52f6576e3ac88305e6/1560144145908-65XJTWKPOSMOF4VUNQ4M/product_shot-11.jpg?format=1000w",
        inCart: false,
        price: "15.99",
    },
    {
        company:"Sega",
        console: "Genesis" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/71w8yKP0qWL._AC_UY436_FMwebp_QL65_.jpg",
        inCart: false,
        price: "19.99",
    },
    {
        company:"Sega",
        console: "Genesis" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/517vs6izMWL._AC_SX679_.jpg",
        inCart: false,
        price: "12.99",
    },
    {
        company:"Sega",
        console: "Genesis" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61eOdCUqiVL._SX522_.jpg",
        inCart: false,
        price: "15",
    },
    {
        company:"Sega",
        console: "Saturn" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/71w8yKP0qWL._AC_UY436_FMwebp_QL65_.jpg",
        inCart: false,
        price: "13.99",
    },
    {
        company:"Sega",
        console: "Saturn" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/517vs6izMWL._AC_SX679_.jpg",
        inCart: false,
        price: "15.00",
    },
    {
        company:"Sega",
        console: "Saturn" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61eOdCUqiVL._SX522_.jpg",
        inCart: false,
        price: "17.00",
    },
    {
        company:"Sony",
        console: "Playstation" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61xYYR827AL._AC_SX679_.jpg",
        inCart: false,
        price: "14.99",
    },
    {
        company:"Sony",
        console: "Playstation" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61rpfFt9qmL._AC_UY436_FMwebp_QL65_.jpg",
        inCart: false,
        price: "10.00",
    },
    {
        company:"Sony",
        console: "Playstation" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/610VfW8kbaL._AC_SX679_.jpg",
        inCart: false,
        price: "7.77",
    },
    {
        company:"Nintendo",
        console: "Nintendo 64" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/81hdKu5JdCL._SX522_.jpg",
        inCart: false,
        price: "10.20",
    },
    {
        company:"Nintendo",
        console: "Nintendo 64" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61bFO8I2YNL._AC_SX679_.jpg",
        inCart: false,
        price: "16.99",
    },
    {
        company:"Nintendo",
        console: "Nintendo 64" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/51obC0-30lL._AC_SX679_.jpg",
        inCart: false,
        price: "14.00",
    },
    {
        company:"Sega",
        console: "Dreamcast" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/7183opehIpL._AC_SX679_.jpg",
        inCart: false,
        price: "15.00",
    },
    {
        company:"Sega",
        console: "Dreamcast" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/71LRfEgshgL._AC_SX679_.jpg",
        inCart: false,
        price: "20.00",
    },
    {
        company:"Sega",
        console: "Dreamcast" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61uYia06YGL._AC_SX679_.jpg",
        inCart: false,
        price: "25.00",
    },
    {
        company:"Sony",
        console: "Playstation 2" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61xYYR827AL._AC_SX679_.jpg",
        inCart: false,
        price: "16.99",
    },
    {
        company:"Sony",
        console: "Playstation 2" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/71jnlaeVCZS._AC_UY436_FMwebp_QL65_.jpg",
        inCart: false,
        price: "13.99",
    },
    {
        company:"Sony",
        console: "Playstation 2" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/610VfW8kbaL._AC_SX679_.jpg",
        inCart: false,
        price: "15.99",
    },
    {
        company:"Nintendo",
        console: "Gamecube" ,
        product: "Power Supply",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/71Uyg0lLqgL._AC_SX679_.jpg",
        inCart: false,
        price: "11.99",
    },
    {
        company:"Nintendo",
        console: "Gamecube" ,
        product: "Display Cable",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61bFO8I2YNL._AC_SX679_.jpg",
        inCart: false,
        price: "12.00",
    },
    {
        company:"Nintendo",
        console: "Gamecube" ,
        product: "Display Adapter",
        inStock: true,
        quantity: 25,
        img: "https://m.media-amazon.com/images/I/61yhinMTyBL._AC_SX679_.jpg",
        inCart: false,
        price: "12.99",
    },  
]


module.exports = productsSeed